import type { Metadata } from "next";
import { lusitana } from './ui/fonts';

import "./globals.css";



export const metadata: Metadata = {
  title: "Test Dirnmov",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lusitana.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
